FAB-94: Main script for data profiling
SeanMcCrossanTUD/TUD-Group-Project pull request #97
Opened 2023-10-20 19:24 UTC by SeanMcCrossanTUD

- Removed flask api scripts
- Edited azure functions to read and output json messages.
- Created main script that checks for messages and runs data quality checks and outputs data profile images
- Created unit test

@D22124491-NaveenMaheswaran please test this, the queue names might be wrong and lets get on a call tomorrow to finish the data prep. I have a unit test to mock the scenario and it works but need to test on the actual environment.

2023-10-20 19:52 UTC, UmamaSumlinTasnuva approved these changes
outputs in JSON format is much better than returning in string type. Also, in all our other codes we're using JSONs everywhere so it syncs well.

2023-10-21 16:33 UTC, D22124491-NaveenMaheswaran requested changes
just make that change other than that looks good, can you run it once let me see if its deleting message from queue as well.

2023-10-21 16:33 UTC, D22124491-NaveenMaheswaran commented on python_da/dq_checks/run_main.py
> +        time.sleep(60)
you put at the end of the function

2023-10-22 13:55 UTC, D22124491-NaveenMaheswaran approved these changes

2023-10-22 13:55 UTC, merged